<TabbedPanel>:#:kivy 
  
    # creating the size
    # and the alignment of the tab 
    size_hint: .5, .5
    pos_hint: {'center_x': .5, 'center_y': .5}
    do_default_tab: False
  

    TabbedPanelItem:
        text: 'Tab 0'
        BoxLayout:
            Label:
                text: 'Press button'
            Button:
                text: 'Click it'

    TabbedPanelItem:
        text: 'Tab 1'
        RstDocument:
            text: '\n'.join(("hola"))